env:
  global:
    - secure: "K4NZeEe6ygzEVCTyupmVj04cai9+/mpzJXRUcmF+MuUPaZ79UL2qYC+mBzuc+pwdpbgcHcbzYo9oqCiY22vcMfb/a9DVvPFf/l4i0eEsiwR5ewZsJH5w/aSy3ljqLyTnDsW9Pen2OBQKTrzTcxEO6R4o0LaQpKG8iYwsKYN4pUDYdxJHaQeCpryIdBa8S2/712F2nXpErnrIXlUnkjwygHebC8bDfz/ZdQrgxzKSFHBB+Es2CkcFjmmCtZtCdvmlO6VmvA1vYWMhLA6aGdYJVpzOHwlie2SSNREHDr/7S16zrbAWlu4PuvgwuXhYaAVPEHvmdDwRInIgIRBJCz1HTPLnSCTLVXeHolGWWbg379pglndNpHKE9ojEvWVeVcbPMJyg0/0xbCIS/EZVYahld2DAbvw2H/SA9hTWNxeOsjJy+k06kiyg2VpXIZT3LOcmbfSpiXabXhabXVDmz9hEyI3U8vfsWFdONcTUcJavMGkmGDcjEnKX999amutU0a8VjP0/RCN8VglLOcZCQLL+k5ZLMQ24hR6Mpt+6wvnvgVeUZwLEQ9nv3HRdNA11wk0OV04lCVd/PU9FGvWINjqD4QhvTEQWe6hCwCA6yFI9H0qu2pZzA2V3OHPy+bej/GR1HfdvAmbZeNQ61Rp4jFP0QGuequuKA8socoYy+/N+HeE="
    - GIT_DEPLOY_DIR=public
    - GIT_DEPLOY_BRANCH=gh-pages
    - GIT_DEPLOY_USERNAME="Travis CI"
    - GIT_DEPLOY_EMAIL=michael@mitchtech.net

branches:
  only:
    - master

install:
  - rm -rf public || exit 0

script:
  - binaries/hugo

after_success:
  - cp .travis.yml public
  - echo "michaeljmitchell.com" > public/CNAME
  - bash deploy.sh