## Basic Configuration
#baseurl = "https://mitchtech.github.io/hugo-michaeljmitchell"
baseurl = "http://michaeljmitchell.com"
builddrafts = false
canonifyurls = false
languageCode = "en-US"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
author = "Michael J. Mitchell, Ph.D."
title = "Michael J. Mitchell, Ph.D."
theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-michaeljmitchellcom"
#googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Michael J. Mitchell, Ph.D."
intro = "Software developer, engineer, scientist, hacker, maker"
#description = "I'm Principal Engineer & Technical Lead of the Customer Experience (CX) Lab at T-Mobile. <br/><br/>My current R&D includes optimization of telemetry collection, aggregation, visualization, monitoring, and anomaly detection platforms as well as modernizing CI/CD/CT infrastructure using open source software and modern DevOps design patterns. Since I joined the lab in 2015, I have also been driving new mobile LTE security research initiatives, prototyping new mobile and IoT product concepts, and developing synthetic user experience automation and analytic tools.<br/><br/>I have a PhD in Computer Science and over a decade of industry experience spanning privacy, security, data science, embedded systems, and context‐aware domains."
description = "Principal Engineer & Technical Lead of [@CX Lab](https://cxlab.tmo.io) [@T-Mobile](https://t-mobile.com). Tech blog [@mitchtech.net](http://mitchtech.net). Previously, [@Mobile Lab](http://mobile.cs.fsu.edu) & [@OS/security](https://www.cs.fsu.edu/) research [@FSU](https://fsu.edu/)."
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Personal Website for Michael J. Mitchell"
keywords = "developer,engineer,scientist,hacker,maker"

## Social Accounts
[params.social]
github = "mitchtech"
linkedin = "mikmitch"
twitter = "michaeljmitchel"
google = "+MichaelMitchell1"
stackoverflow = "1454615"
youtube = "mitchtechnet"
email = "michael@mitchtech.net"
#facebook = ""
#instagram = ""

## Extras
[params.extra]
copyright = "© 2017. Michael J. Mitchell."
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "blog"
    weight = 200
    identifier = "blog"
    url = "http://mitchtech.net"
[[menu.main]]
    name = "code"
    weight = 300
    identifier = "code"
    url = "https://github.com/mitchtech"
[[menu.main]]
    name = "publications"
    identifier = "publications"
    weight = 600
    url = "/publications/"
[[menu.main]]
    name = "resume"
    identifier = "resume"
    weight = 700
    url = "https://www.dropbox.com/s/peyfb5e659s3ixc/Michael_J_Mitchell_Resume.pdf?dl=1"
